### PR TITLE
feat: allow to ignore version check

### PR DESCRIPTION
**Pull request by omerlh**
As discussed on #118 that's for supporting weird BAI files with wrong header 🤷

### CODE REVIEW

**Comment by adamdecaf** [comment]
@omerlh can you run `gofmt -s -w` on that main.go file?

**Comment by omerlh** [comment]
Yeah sure!

**Comment by adamdecaf** [comment]
Sorry I missed this before but we don't want to be passing booleans around. I thought you were talking about an Options struct that goes on a BAI2 File, Reader, Writer, ValidateWith(...) which has an `IgnoreVersion bool` field.

This change would be a breaking change as-is and booleans make for bad parameters.

**Comment by omerlh** [comment]
I am happy to change the code to support options parameters, but it needs to be populated from the CLI args... Also we can do that non-breaking with default values

**Comment by adamdecaf** [comment]
@omerlh I moved ignoreVersion to an Options struct. Thoughts?

**Comment by omerlh** [comment]
Looking good!

**Pull request merged**
